Front/feature/component category select
lucesitaliss/ProductosCompras pull request #6
Opened 2022-10-05 18:59 UTC by lucesitaliss

2022-10-05 19:06 UTC, lucesitaliss commented
Conectin <select> with BD,

2022-10-08 01:15 UTC, larts85 requested changes

2022-10-08 01:15 UTC, larts85 commented on client/src/components/NewCart/CategorySelect/index.js
> +  //setCategorys(GetCategorys)
no código comentado

2022-10-08 01:15 UTC, larts85 commented on client/src/components/NewCart/CategorySelect/index.js
> +    GetCategorys()
camelCase, falta de ortografía

2022-10-08 01:15 UTC, larts85 commented on .github/workflows/eslint.yml
> +
vamos a eliminar este archivo y a hacer el pipeline manualmente, siguiendo este video:
https://youtu.be/sIhm4YOMK6Q hasta donde configura la parte de `eslint`.

2022-10-08 01:15 UTC, larts85 commented on client/src/components/NewCart/CategorySelect/index.js
> +      <select >
aca faltan las propiedades del select y las options, name vale id y que se yo, ademas cada elemento que se renderiza en un map debe tener la propiedad key.

2022-10-08 01:15 UTC, larts85 commented on client/src/components/NewCart/CategorySelect/index.js
> +      <select >
tampoco veo lógica de que pasa cuando se selecciona un elemento, ni como se representan esos elemento visualmente.

2022-10-08 02:40 UTC, lucesitaliss commented on client/src/components/NewCart/CategorySelect/index.js
> +      <select >
Porque no está terminado. estuve haciendo la otra parte del back para poder conectar los componentes. La idea es seleccionar la categoría y pasar esa info para q se renderice solo los productos asociados a esa categoria.

2022-10-08 03:00 UTC, merged